version: '3.6'

services:

  app:
    container_name: dropwizard-poc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    platform: linux/amd64
    restart: always